### ISSUE TITLE
Brukerregistrering på events fra før brukeren var opprettet 

### ISSUE THREAD

**Issue by JacobTheisen** [TIHLDE/pythons_event_registration#13]
Brukere blir lagt til i listen over brukere som skal ha bot for registering til et event til tross for at brukeren ikke eksisterte på eventets tidspunkt. Feks står alle nye brukere (lagt til 31.08) på listen over brukere som skal ha bot for åpen trening (24.08).

Hvis dette er meningen er det nice om det skilles på brukere som feilregistrerte til eventet og nye brukere som ikke eksisterte på til eventet på en hensiktsmessig måte. 
Peace out✌️

**Comment by maxschau** [comment]
Lagt til en sjekk på det nå. Tror det skal være good
