### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by filibeee** [TIHLDE/pythons_event_registration#15]
Når jeg skal logge inn er det sånn 6 Filip Bergli profiler, men det er bare én Filip Bergli under spillere. Vet ikke helt hva som har skjedd her...

**Comment by olros** [comment]
Var av en eller annen grunn laget 6 stk Filip Bergli som så er blitt deaktivert, viser ikke lengre deaktiverte profiler i logg-inn nå

**Comment by filibeee** [comment]
Ikkesant, takk!!

Fra: Olaf Rosendahl ***@***.***>
Dato: mandag, 5. september 2022 kl. 19:10
Til: TIHLDE/pythons_event_registration ***@***.***>
Kopi: Filip Røkke Bergli ***@***.***>, Author ***@***.***>
Emne: Re: [TIHLDE/pythons_event_registration] Bug (Issue #15)

Var av en eller annen grunn laget 6 stk Filip Bergli som så er blitt deaktivert, viser ikke lengre deaktiverte profiler i logg-inn nå
