### ISSUE TITLE
Kamp-statistikk

### ISSUE THREAD

**Issue by filibeee** [TIHLDE/pythons_event_registration#20]
Nå føler jeg vi er kravstore her, men det hadde vært kult å kunne vise hvem som har scoret mål, målgivende, og kort på siden, som vi legger inn manuelt etter kamp.

**Comment by maxschau** [comment]
Har sett på det! Har laget logikk for det backend, men må finne en nice måte å gjøre det i brukergrensesnittet også. Kanskje @olros har tid for eks? :)

**Comment by olros** [comment]
Kan checke ut branchen din etterhvert ja @maxschau

**Comment by olros** [comment]
Fullført! Lager nytt issue på en ledertavle over flest mål/assist/kort/osv
