### ISSUE TITLE
Verv-historikk

### ISSUE THREAD

**Issue by olros** [TIHLDE/pythons_event_registration#32]
Obersikt over hvem som innehar og tidligere har hatt ulike verv

**Comment by maxschau** [comment]
Behøver:

- [ ] Frontend for CRUD-operasjoner for verv
- [ ] Frontend for å vise historikken
- [ ] Backend + DB for håndtering av logikk rundt verv

**Comment by olros** [comment]
Må kanskje revidere menyen også for å få plass til enda en link til en ny side
