### ISSUE TITLE
Statistikk

### ISSUE THREAD

**Issue by olros** [TIHLDE/pythons_event_registration#7]
Som admin/(alle?) ønsker jeg å se statistikk for oppmøte på treninger, kamper og sosialt. Dette kan gå på både hele kategoriene, for eksempel gjennomsnittlig oppmøte på trening er 65%, men også på individer der "Trond møter opp på 92% av treninger" med "ledertavle" for eksempel.

**Comment by maxschau** [comment]
Enig. Kult også med ledertavle over kamper
