### ISSUE TITLE
Se på andre hosting-muligheter

### ISSUE THREAD

**Issue by maxschau** [TIHLDE/pythons_event_registration#8]
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/49594236/187086880-42787178-19bf-488e-b00a-bb63fe10c4a6.png">

https://blog.heroku.com/next-chapter

**Comment by olros** [comment]
En fin liste ligger her: https://gist.github.com/bmaupin/0ce79806467804fdbbf8761970511b8c

Ikke så veldig mange gode alternativer:

- [filess.io](https://filess.io/#pricing) -> Max 10mb lagring, i praksis 1mb etter å ha laget tabeller. Tror det fort blir fullt
- [Clever Cloud](https://www.clever-cloud.com/en/pricing) -> 250mb lagring. Max 5 forbindelser, kan skape problemer ettersom Next.js kjører serverless
- [Supabase.io](https://supabase.com/pricing) -> 500mb lagring. Prosjektet deaktiveres etter 1 uke uten aktivitet, kan aktiveres igjen å få tilbake data, men usikker på om det skjer automatisk ved request eller om admin-siden må åpnes. (Kan kanskje "hacke" dette med en cron-job som jevnlig sender forespørsler?)

**Comment by olros** [comment]
Kan forsåvidt også høre med @trthingnes og Index om vi kan sette opp en Postgres-database i deres Azure. Koster 1800 i året, noe som det bør være plass til innenfor gratis-kvoten hos Azure.

Den kan lages slik at den ikke kun er for Pythons, men at vi bruker en database i den og evt andre prosjekter også kan få sin egen database samme instans.

Tanker @trthingnes?
